// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tipkizmayytovxzqtllv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpcGtpem1heXl0b3Z4enF0bGx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODA1NDEsImV4cCI6MjA3MDg1NjU0MX0.J4EFtqUtTrV2XJY6seMkm7nazD0TWekqqyUtTvXuHd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});